language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get install build-essential
  - sudo apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev

before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..

script: make
